### ISSUE TITLE
DECIMAL column on MySQL

### ISSUE THREAD

**Issue by subc** [naoina/migu#9]
Ridgepole can use decimal columun. Will not 'migu' also be available for use?

```
$ migu dump -h 127.0.0.1 -u root {db_name} ./dump.go
BUG: unexpected data type: decimal
```

**Comment by naoina** [comment]
Currently, it is not supported on migu, but I will support it. Of course, Pull-Request is always welcome!

**Comment by naoina** [comment]
@subc I have just implemented DECIMAL support. Thank you.
